### ISSUE TITLE
Flaky integration tests

### ISSUE THREAD

**Issue by sed-i** [canonical/grafana-k8s-operator#137]
### Bug Description
`test_selfmonitoring_dashboard::test_remove` occasionally fails.

After removing prom,
```python
await ops_test.model.applications[prometheus_app_name].remove()
```

The test makes an assertion
```python
relation_removed_dashboards = await get_grafana_dashboards(ops_test, grafana_app_name, 0)
assert relation_removed_dashboards == []
```

That fails. Occasionally.
https://github.com/canonical/grafana-k8s-operator/actions/runs/3177380221/jobs/5177760631#step:5:801

### To Reproduce

Run itests.

### Environment

GitHub runner

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/runner/work/grafana-k8s-operator/grafana-k8s-operator/tests/integration/test_selfmonitoring_dashboard.py", line 88, in test_remove
    assert relation_removed_dashboards == []
AssertionError: assert [{'id': 1, 'i...eta': 0, ...}] == []
  Left contains one more item: {'id': 1, 'isStarred': False, 'slug': '', 'sortMeta': 0, ...}
  Full diff:
    [
  -  ,
  +  {'id': 1,
  +   'isStarred': False,
  +   'slug': '',...
```

**Comment by sed-i** [comment]
Seems like it fails more frequently now
https://github.com/canonical/grafana-k8s-operator/actions/runs/3184129557/jobs/5199389512#step:5:809

**Comment by rbarry82** [comment]
This was actually flaky before, and to make it less flaky, removing the "self-monitoring" relation actually [completely restarts Grafana after deleting the provisioning file](https://github.com/canonical/grafana-k8s-operator/blob/main/src/charm.py#L342). I'll try with microk8s 1.25 locally to see if I can make this happen more often locally.

It's completely crazy that the `ModelConfigChange` workaround [here](https://github.com/canonical/grafana-k8s-operator/pull/135/commits/b226268712ac37a24d271e71b1c93e65491b6031) increased reliability, because Grafana doesn't use update-status... at all. So that change is affecting Juju behavior only, yet increases reliability of tests in a charm which literally do not respond to that event.

**Comment by sed-i** [comment]
Still flaky:

- `test_selfmonitoring_dashboard`: [still fails](https://github.com/canonical/grafana-k8s-operator/actions/runs/3492470981/jobs/5854092283).
- `test_grafana_dashboard_relation_data_with_grafana_tester`: Test [times out](https://github.com/canonical/grafana-k8s-operator/actions/runs/3492470981/jobs/5846626784) after 6h.

**Comment by sed-i** [comment]
[Still fails](https://github.com/canonical/grafana-k8s-operator/actions/runs/3658389427/jobs/6183130254).

**Comment by rbarry82** [comment]
Unfortunately, still irrelevant. There's just nothing actionable other than deleting the test or waiting until we move to self-hosted infrastructure. It only fails in GH runners, and only sometimes, and seems to be related to speed or resource starvation.
