### ISSUE TITLE
Can't access grafana dashboard without using `https`

### ISSUE THREAD

**Issue by orfeas-k** [canonical/grafana-k8s-operator#304]
After following the [Microk8s tutorial](https://charmhub.io/topics/canonical-observability-stack/tutorials/install-microk8s) locally, I 'm trying to access `grafana` through the url exposed by `juju show-unit catalogue/0 | grep url` and I 'm getting the error below on browser:

```
This page isn’t working
192.168.2.5 redirected you too many times.
```

while curling the same address returns

```
curl 192.168.2.5/cos-grafana -I
HTTP/1.1 301 Moved Permanently
```

@dstathis prompted me to add `https://` in front of the URL which made it work, but that's not what I expected.

**Comment by lucabello** [comment]
This is due to the stable release using the Grafana 10 image, which has some modifications our charm isn't yet ready for :)

In the meantime, the charm was updated to go back to the Grafana 9 image until we fix that, but the change hadn't made it to `candidate` or `stable` yet, which is why you got this.

It's fixed now! :)
