### ISSUE TITLE
Multiple errors in documentation and on charmhub.io

### ISSUE THREAD

**Issue by erik78se** [canonical/grafana-k8s-operator#57]
Multiple issues with the documentation for the VM charm in charmhub.io

1. The documentation URL for the VM charm points to the k8 repo. Is this the right place to file bugs also for the VM charm? Should I really file errors about the VM charm in here?

2. The documentation on how to deploy is for k8 charms. So, I get confused what this charm is about and how to use it.

3. The documentation states it can relate to charmcraft-prometheus, but it cant. "ERROR: No relations found" (See separate issue: ) 

![image](https://user-images.githubusercontent.com/850603/152130064-c889b04a-4b70-4fb5-9aea-00fe66957322.png)

**Comment by jnsgruk** [comment]
Hi @erik78se -- the charms that the Observability team are working on right now are all targeting Kubernetes. The team plans to ship the stack essentially as an "appliance" on MicroK8s. The charms prefixed `charmcraft-` should be considered deprecated, we're in the process of cleaning those up.

The documentation about the new stack has a homepage here: https://juju.is/docs/lma2

There is a way for you do deploy the Charmed Observability Stack (COS) Lite into MicroK8s, then hook up your VM based applications using Cross-Model Relations, though. I think @mmanciop or @simskij should be able to point you in the right direction for that -- but this issue seems to relate to the "wrong" charms.

Sorry for any confusion here!

**Comment by simskij** [comment]
> Edit: Found it! Check out the COS Proxy charm for a simple way to grab alerts/logs from your machine based models.

This is the way 👍🏽

**Comment by erik78se** [comment]
But, why is this charm then in charmhub at all. It also deploys.

However, the documentation is totally bogus.

When I'm following build instructions, is also creates a k8 charm ... which happily deploys (but obviously errors).

**Comment by simskij** [comment]
Yeah, it should definitely be cleaned up. It's unfortunate that the charm listing points at this repo (it really shouldn't). Sorry for the confusion.
