### ISSUE TITLE
Allow opt-out of automatic injection of topology filters

### ISSUE THREAD

**Issue by simskij** [canonical/grafana-k8s-operator#95]

**Comment by simskij** [comment]
So after a detailed discussion yesterday, we decided the following:

- No changes will be made to the constructor.
- Whether or not to opt-out of the injection is done through calling `add_dashboard` manually.

The only use case for this currently is `cos-configuration`.

**Comment by rbarry82** [comment]
Perfect. After finishing the code walkthrough yesterday, we weren't exactly sure whether it would be constructor for global, optarg in `add_dashboard`, or both.

To preserve the sanity of... everyone else, the major consideration with `cos-config` is that, after a debate, `cos-config` is doing things the "easy way" rather than the "hard way". That is to say that, even though the essential flows of `cos-config` _could_ have been done using the public APIs, it would have been more up-front work versus adding a back-channel private method, which is what ended up going into Prometheus/Loki/Grafana.

`cos-config` does not currently use `add_dashboard`, and `add_dashboard` has 2 (possibly 3) design concerns as it relates to `cos-config`:

* Since the objects are prepended with `prog:` rather than `file:`, they are not automatically purged from data on a refresh of the dir, since we assume that authors no not want explicitly added dashboards to flicker in and out of existence during charm lifecycle events.
* `add_dashboard` expects dashboards one-at-a-time as "raw" text rather than reading a file in itself. It then updates the relation data. If something like `cos-config` is adding a large number of dashboards, that's a lot of events and churn
* The logic in `cos-config` would need to change significantly. Even if `add_dashboard` could take a list (or we had `add_dashboards` instead, `add_dashboard_from_file` which could take either as filepath objects and did it inside Grafana, it's still a change)

Without major changes to `cos-config`, which, to be clear, I'm in favor of, along with stripping out the backchannel methods from prometheus/loki, the best way to solve this for `cos-config` is to also include an optional argument [here](https://github.com/canonical/grafana-k8s-operator/blob/main/lib/charms/grafana_k8s/v0/grafana_dashboard.py#L839) (this is called by `_reinitialize_dashboard_data`, which is the `cos-config` backchannel) to pass it on.

Making the gist of this comment, basically, "do we put in more work now to 'fix' `cos-config` to use the public API and stop maintaining things like `PrometheusRulesProvider` and back-channel methods with one (internal) consumer?" or do we do what is expedient for `cos-config`?

Either way, it will be included in `add_dashboard`, just a comment that putting it there won't actually resolve the scenario with `cos-config` without work on one side or the other.

**Comment by simskij** [comment]
> do we put in more work now to 'fix' cos-config to use the public API and stop maintaining things like PrometheusRulesProvider and back-channel methods with one (internal) consumer?" or do we do what is expedient for cos-config?

I vote for the former. `PrometheusRulesProvider` was a mistake and should be rectified.
